WebHomeStay/WebHomeStay/Controllers/DatPhongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebHomeStay.Models;


namespace WebHomeStay.Controllers
{
    public class DatPhongController : Controller
    {
        DatabaseDataContext db = new DatabaseDataContext();
        // GET: DatPhong
        public ActionResult Index()
        {
            List<PHONG> p = db.PHONGs.ToList();

            return View(p);
        }

        public ActionResult LoaiPhong(string Maloai)
        {
            var listPhong = db.PHONGs.Where(s => s.MALOAIPHONG == Maloai).ToList();

            if (listPhong.Count == 0)
            {
                ViewBag.TB = "Không tìm thấy phòng nào thuộc mã loại " + Maloai;
                ViewBag.LoaiPhong = ""; // Không có phòng, đặt LoaiPhong là chuỗi trống
            }
            else
            {
                // Lấy tên loại phòng từ db.LOAIPHONGs
                string tenLoai = db.LOAIPHONGs
                    .Where(s => s.MALOAI == Maloai)
                    .Select(s => s.TENLOAI)
                    .FirstOrDefault();

                ViewBag.LoaiPhong = tenLoai;
            }

            return View(listPhong);
        }

        public ActionResult CTPhong(string ma)
        {
            var phong = db.PHONGs.SingleOrDefault(t => t.MAPHONG.Equals(ma));

            if (phong == null)
            {
                return HttpNotFound();
            }
            return View(phong);
        }


        [HttpGet]
        public ActionResult DatPhongKH()
        {
            string maPhong = RouteData.Values["id"] as string;

            if (string.IsNullOrEmpty(maPhong))
            {
                // Xử lý khi giá trị không tồn tại
                return HttpNotFound();
            }
            ViewBag.DichVuList = new SelectList(db.DVus, "MADV", "TenDV");
            var phong = db.PHONGs.FirstOrDefault(s => s.MAPHONG.Equals(maPhong));

            if (phong == null)
            {
                // Xử lý khi không tìm thấy phòng
                return HttpNotFound();
            }
            ViewBag.phong = phong;
            ViewBag.dsnguoidung = db.KHACHHANGs.ToList();
           
            return View();
        }

        [HttpPost]
        public ActionResult DatPhongKH(HOADON hd, CTHD ct, FormCollection f)
        {
           
            var makh = f["makh"];
            var mahd = f["mahd"];
            var ngaytao = f["ngaytao"];
            var madv = f["madv"];
            var maphong = f["maph"];
            var tongtien = f["tongtien"];
            var giamgia = f["giamgia"];
            var sldichvu = f["sldichvu"];


            hd.MAKH = makh;
            hd.NGAYTAO = DateTime.Now;

            db.HOADONs.InsertOnSubmit(hd);
            db.SubmitChanges();

            
            IList<CTHD> cthds = new List<CTHD>();
            //Khúc này sẽ add từng CTHD vào 
            ct.MADV = 1;
            ct.MAHD = hd.MAHD;
            ct.MAPHONG = maphong;

            db.CTHDs.InsertOnSubmit(ct);
            db.SubmitChanges();
            ct.SLDICHVU = 1;
            ct.TONGTIENTHANHTOAN = ct.DVu.DONGIA * ct.SLDICHVU + ct.PHONG.LOAIPHONG.GIAPH;

            db.SubmitChanges();
            var phong = db.PHONGs.SingleOrDefault(p => p.MAPHONG == maphong);
            if (phong != null)
            {
                // In ra giá trị trạng thái phòng để kiểm tra
                Console.WriteLine("Trạng thái phòng trước khi cập nhật: " + phong.TRANGTHAI);

                // Kiểm tra và cập nhật trạng thái phòng chỉ khi phòng đang ở trạng thái trống
                if (phong.TRANGTHAI == "Trống")
                {
                    phong.TRANGTHAI = "Đã thuê";
                    db.SubmitChanges();
                }
            }

           
            return RedirectToAction("Index");
        }


    }
}

WebHomeStay/WebHomeStay/Views/DatPhong/CTPhong.cshtml
@model WebHomeStay.Models.PHONG
@{
    ViewBag.Title = "Chi tiết phòng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .card {
        position: relative;
        overflow: hidden;
    }

        .card img {
            width: 100%;
            height: 145px;
            max-width: 100%; /* Đặt tối đa chiều rộng */
            display: block; /* Loại bỏ khoảng trắng dưới hình ảnh */
            margin: 0 auto; /* Căn giữa hình ảnh trong thẻ card */
        }
</style>
<div class="container mt-4">
    <h3>Chi Tiết Phòng</h3>
    <div class="row">
        <div class="col-md-6">
            <p><strong>Mã Phòng:</strong> @Model.MAPHONG</p>
            <p><strong>Tên Phòng:</strong> @Model.TENPHONG</p>
            <p><strong>Loại Phòng:</strong> @(Model.LOAIPHONG != null ? Model.LOAIPHONG.TENLOAI : "Không có")</p>
            <p><strong>Số Lượng Người Ở:</strong> @Model.SOLUONGNGUOIO Người</p>
            <p><strong>Mô Tả:</strong> Phòng tiện nghi với thiết bị hiện đại, không gian thoải mái và trang thiết bị chất lượng.<br /> Trải nghiệm kỳ nghỉ đẳng cấp tại phòng chúng tôi!</p>
            <p><strong>Dịch Vụ Đi Kèm:</strong></p>
            <ul>
                <li>Wifi miễn phí</li>
                <li>TV màn hình phẳng</li>
                <li>Dịch vụ phòng hàng ngày</li>
                <li>Miễn phí nước suối và đồ uống trong minibar</li>
                <li>Phòng tắm riêng với vòi sen và bồn tắm</li>
                <li>Điều hòa nhiệt độ</li>
                <li>Máy pha cà phê và ấm đun nước</li>
                <li>Bàn làm việc thoải mái</li>
                
            </ul>
           
            <a href="@Url.Action("Index", "DatPhong")" class="btn btn-primary">Quay Lại Danh Sách Phòng</a>
        </div>
        <div class="col-md-6 text-center">
            <img src="~/img/img/@(Model.MAPHONG).jpg" style="max-width:100%; margin-bottom:20px" />
        </div>
    </div>
</div>

WebHomeStay/WebHomeStay/Views/DatPhong/DatPhongKH.cshtml
@using WebHomeStay.Models;
@model WebHomeStay.Models.HOADON

@{
    ViewBag.Title = "DatPhongKH";
    Layout = "~/Views/Shared/_Layout.cshtml";
    KHACHHANG kh = Session["KH"] as KHACHHANG;
    PHONG phong = ViewBag.phong;
    DVu dv = ViewBag.MaDichVu;
}



@if (kh == null)
{
    <p class="text-danger">Bạn chưa đăng nhập, vui lòng đăng nhập để đặt phòng</p>
}
else
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="well well-sm">
                        <form class="form-horizontal" role="form">
                            <fieldset>
                                <legend class="text-center">Thông Tin Đặt Phòng</legend>

                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="makh">Mã Khách Hàng</label>
                                    <div class="col-md-8">
                                        @Html.TextBox("makh", kh.MAKH, new { id = "makh", @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="tenkh">Tên Khách Hàng</label>
                                    <div class="col-md-8">
                                        @Html.TextBox("tenkh", kh.HOTEN, new { id = "tenkh", @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="maph">Mã Phòng</label>
                                    <div class="col-md-8">
                                        @Html.TextBox("maph", phong.MAPHONG, new { id = "maph", @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="tenphong">Tên Phòng</label>
                                    <div class="col-md-8">
                                        @Html.TextBox("tenphong", phong.TENPHONG, new { id = "tenphong", @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="giatien">Giá tiền</label>
                                    <div class="col-md-8">
                                        @Html.TextBox("giatien", String.Format("{0:0,0 VNĐ}", phong.LOAIPHONG.GIAPH), new { id = "giatien", @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>


                                <!-- Đẩy ảnh phòng về bên phải -->
                                <div class="form-group">
                                    <div class="col-md-8 col-md-offset-4">
                                        <img src="~/img/img/@(phong.MAPHONG).jpg" alt="Ảnh Phòng" class="img-responsive" style="margin-top: 20px; margin-bottom: 20px;" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-4 col-md-8">
                                        <input type="submit" value="Đặt Phòng" class="btn btn-primary" />
                                    </div>
                                </div>

                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    }
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebHomeStay/WebHomeStay/Views/DatPhong/Index.cshtml
@model IEnumerable<WebHomeStay.Models.PHONG>


@{
    ViewBag.Title = "Danh sách phòng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .card {
        position: relative;
        overflow: hidden;
    }

        .card img {
            width: 100%;
            height: 145px;
            max-width: 100%; /* Đặt tối đa chiều rộng */
            display: block; /* Loại bỏ khoảng trắng dưới hình ảnh */
            margin: 0 auto; /* Căn giữa hình ảnh trong thẻ card */
        }

    .custom-action {
        background-color: #f8f9fa; /* Màu nền div */
        padding: 15px;
        margin-top: 10px;
        border-radius: 8px;
    }

        .custom-action ul {
            list-style: none; /* Loại bỏ dấu chấm đầu dòng */
            padding: 0; /* Loại bỏ padding mặc định của danh sách */
        }

        .custom-action li {
            margin-bottom: 10px; /* Khoảng cách giữa các mục danh sách */
            display: block; /* Hiển thị các mục danh sách dưới dạng block để không có dạng liên kết */
        }
</style>


<div class="container mt-4">
    <h3><b>Danh Sách Phòng</b></h3>
    <div class="row">
        <div class="col-lg-3">
            <div class="custom-action">
                <h2><i class="fa fa-home"></i>Chọn theo loại</h2>
                @Html.Action("LoaiPhong", "Home")
            </div>
        </div>
        <div class="col-lg-9">
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
                @foreach (var pv in Model)
                {
                    <div class="col-lg-4">
                        @if (pv != null)
                        {
                        <div class="card phong p-3">
                            <a href="@Url.Action("CTPhong", "Datphong", new { ma = pv.MAPHONG })">
                                <img src="~/img/img/@(pv.MAPHONG).jpg"/>
                            </a>
                            <span style="margin-top:10px;"><b>@pv.TENPHONG</b></span><br />
                            <label>Loại Phòng: @(pv.LOAIPHONG != null ? pv.LOAIPHONG.TENLOAI : "Không có")</label><br />
                            <span class="gia-thue">Số người ở: @pv.SOLUONGNGUOIO Người </span><br />
                            <span>Trạng thái: @pv.TRANGTHAI</span><br />
                            <span>Giá: @String.Format("{0:0,0 VNĐ}", pv.LOAIPHONG.GIAPH)</span><br />

                            @if (pv.TRANGTHAI == "Đã thuê")
                            {
                                <button class="btn btn-dat-phong" disabled>ĐẶT PHÒNG</button>
                            }
                            else
                            {
                                <button class="btn btn-primary btn-dat-phong" onclick="location.href = '/DatPhong/DatPhongKH/@pv.MAPHONG'">ĐẶT PHÒNG</button>
                                

                            }
                        </div>
                        }
                        else
                        {
                            <div class="phong">
                                <span>Phòng không hợp lệ</span><br />
                            </div>
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</div>

WebHomeStay/WebHomeStay/Views/DatPhong/LoaiPhong.cshtml
@model IEnumerable<WebHomeStay.Models.PHONG>


@{
    ViewBag.Title = "Loại phòng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .card {
        position: relative;
        overflow: hidden;
    }

        .card img {
            width: 100%;
            height: 145px;
            max-width: 100%; /* Đặt tối đa chiều rộng */
            display: block; /* Loại bỏ khoảng trắng dưới hình ảnh */
            margin: 0 auto; /* Căn giữa hình ảnh trong thẻ card */
        }

</style>
<div class="container mt-4">
    <h3><b>Danh Sách Phòng Theo Loại: @ViewBag.LoaiAo</b></h3>
    @if (Model.Count() > 0)
    {
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            @foreach (var pv in Model)
            {
                <div class="col-lg-3">
                    @if (pv != null)
                    {
                    <div class="card phong p-3">
                        <a href="@Url.Action("CTPhong", "Datphong", new { ma = pv.MAPHONG })">
                            <img src="~/img/img/@(pv.MAPHONG).jpg" />
                        </a>
                        <span style="margin-top:10px;"><b>@pv.TENPHONG</b></span><br />
                        <label>Loại Phòng: @(pv.LOAIPHONG != null ? pv.LOAIPHONG.TENLOAI : "Không có")</label><br />
                        <span class="gia-thue">Số người ở: @pv.SOLUONGNGUOIO Người </span><br />
                        <span>Trạng thái: @pv.TRANGTHAI</span><br />
                        <span>Giá: @String.Format("{0:0,0 VNĐ}", pv.LOAIPHONG.GIAPH)</span><br />
                        @if (pv.TRANGTHAI == "Đã thuê")
                        {
                            <button class="btn btn-dat-phong" disabled>ĐẶT PHÒNG</button>
                        }
                        else
                        {
                            <button class="btn btn-primary btn-dat-phong" onclick="location.href = '/DatPhong/DatPhongKH/@pv.MAPHONG'">ĐẶT PHÒNG</button>
                        }
                    </div>
                    }
                    else
                    {
                        <div class="phong">
                            <span>Phòng không hợp lệ</span><br />
                        </div>
                    }
                </div>
            }
        </div>
    }
    else
    {
        <p>Không có phòng nào thuộc loại này.</p>
    }
</div>